package entidades;
// Generated 02/11/2015 06:22:45 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleReparacion generated by hbm2java
 */
@Entity
@Table(name="detalle_reparacion"
    ,catalog="bdreparaciones"
)
public class DetalleReparacion  implements java.io.Serializable {


     private Integer idDetalleReparacion;
     private Piezas piezas;
     private Reparaciones reparaciones;
     private Integer unidades;

    public DetalleReparacion() {
    }

	
    public DetalleReparacion(Piezas piezas, Reparaciones reparaciones) {
        this.piezas = piezas;
        this.reparaciones = reparaciones;
    }
    public DetalleReparacion(Piezas piezas, Reparaciones reparaciones, Integer unidades) {
       this.piezas = piezas;
       this.reparaciones = reparaciones;
       this.unidades = unidades;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDetalle_Reparacion", unique=true, nullable=false)
    public Integer getIdDetalleReparacion() {
        return this.idDetalleReparacion;
    }
    
    public void setIdDetalleReparacion(Integer idDetalleReparacion) {
        this.idDetalleReparacion = idDetalleReparacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Piezas_idPiezas", nullable=false)
    public Piezas getPiezas() {
        return this.piezas;
    }
    
    public void setPiezas(Piezas piezas) {
        this.piezas = piezas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Reparaciones_idReparaciones", nullable=false)
    public Reparaciones getReparaciones() {
        return this.reparaciones;
    }
    
    public void setReparaciones(Reparaciones reparaciones) {
        this.reparaciones = reparaciones;
    }

    
    @Column(name="unidades")
    public Integer getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(Integer unidades) {
        this.unidades = unidades;
    }




}


