package entidades;
// Generated 02/11/2015 06:22:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Piezas generated by hbm2java
 */
@Entity
@Table(name="piezas"
    ,catalog="bdreparaciones"
)
public class Piezas  implements java.io.Serializable {


     private Integer idPiezas;
     private String descripcion;
     private BigDecimal precio;
     private Integer stock;
     private Set<DetalleReparacion> detalleReparacions = new HashSet<DetalleReparacion>(0);

    public Piezas() {
    }

    public Piezas(String descripcion, BigDecimal precio, Integer stock, Set<DetalleReparacion> detalleReparacions) {
       this.descripcion = descripcion;
       this.precio = precio;
       this.stock = stock;
       this.detalleReparacions = detalleReparacions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPiezas", unique=true, nullable=false)
    public Integer getIdPiezas() {
        return this.idPiezas;
    }
    
    public void setIdPiezas(Integer idPiezas) {
        this.idPiezas = idPiezas;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="precio", precision=4)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    
    @Column(name="stock")
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="piezas")
    public Set<DetalleReparacion> getDetalleReparacions() {
        return this.detalleReparacions;
    }
    
    public void setDetalleReparacions(Set<DetalleReparacion> detalleReparacions) {
        this.detalleReparacions = detalleReparacions;
    }




}


