package entidades;
// Generated 02/11/2015 06:22:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reparaciones generated by hbm2java
 */
@Entity
@Table(name="reparaciones"
    ,catalog="bdreparaciones"
)
public class Reparaciones  implements java.io.Serializable {


     private Integer idReparaciones;
     private Vehiculo vehiculo;
     private String matricula;
     private String descripcion;
     private Date fechaEntrada;
     private Date fechaSalida;
     private Set<DetalleReparacion> detalleReparacions = new HashSet<DetalleReparacion>(0);

    public Reparaciones() {
    }

	
    public Reparaciones(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public Reparaciones(Vehiculo vehiculo, String matricula, String descripcion, Date fechaEntrada, Date fechaSalida, Set<DetalleReparacion> detalleReparacions) {
       this.vehiculo = vehiculo;
       this.matricula = matricula;
       this.descripcion = descripcion;
       this.fechaEntrada = fechaEntrada;
       this.fechaSalida = fechaSalida;
       this.detalleReparacions = detalleReparacions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idReparaciones", unique=true, nullable=false)
    public Integer getIdReparaciones() {
        return this.idReparaciones;
    }
    
    public void setIdReparaciones(Integer idReparaciones) {
        this.idReparaciones = idReparaciones;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vehiculo_idVehiculo", nullable=false)
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }

    
    @Column(name="matricula", length=45)
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaEntrada", length=10)
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaSalida", length=10)
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="reparaciones")
    public Set<DetalleReparacion> getDetalleReparacions() {
        return this.detalleReparacions;
    }
    
    public void setDetalleReparacions(Set<DetalleReparacion> detalleReparacions) {
        this.detalleReparacions = detalleReparacions;
    }




}


