package entidades;
// Generated 02/11/2015 06:22:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name="vehiculo"
    ,catalog="bdreparaciones"
)
public class Vehiculo  implements java.io.Serializable {


     private Integer idVehiculo;
     private Cliente cliente;
     private String marca;
     private String modelo;
     private String color;
     private String placa;
     private Double km;
     private Set<Reparaciones> reparacioneses = new HashSet<Reparaciones>(0);

    public Vehiculo() {
    }

	
    public Vehiculo(Cliente cliente) {
        this.cliente = cliente;
    }
    public Vehiculo(Cliente cliente, String marca, String modelo, String color, String placa, Double km, Set<Reparaciones> reparacioneses) {
       this.cliente = cliente;
       this.marca = marca;
       this.modelo = modelo;
       this.color = color;
       this.placa = placa;
       this.km = km;
       this.reparacioneses = reparacioneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idVehiculo", unique=true, nullable=false)
    public Integer getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Cliente_idCliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="Marca", length=45)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    
    @Column(name="modelo", length=45)
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    
    @Column(name="color", length=45)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    @Column(name="placa", length=10)
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }

    
    @Column(name="km", precision=22, scale=0)
    public Double getKm() {
        return this.km;
    }
    
    public void setKm(Double km) {
        this.km = km;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vehiculo")
    public Set<Reparaciones> getReparacioneses() {
        return this.reparacioneses;
    }
    
    public void setReparacioneses(Set<Reparaciones> reparacioneses) {
        this.reparacioneses = reparacioneses;
    }




}


